FROM python:3.13-slim
WORKDIR /app
COPY ./chroma_loader /app
COPY ./rag_corpus/staged /app/rag_corpus/
RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt
CMD ["python", "chroma_loader.py"]
