FROM python:3.13-slim
WORKDIR /app
COPY ./chat_backend /app
COPY ./rag_corpus/staged /app/rag_corpus/
RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt
EXPOSE 8001
CMD ["uvicorn", "app:app","--host","0.0.0.0","--port","8001"]
